### ISSUE TITLE
Add Images via "+" button

### ISSUE THREAD

**Issue by Vannsl** [Vannsl/vue-contenteditable-form#15]
# Story

As a user, I want to be able to add images to my form by clicking on a "plus button" which opens my file browser.

## Acceptance Critieras

- [x] There's a button with "+" next to all blocks
- [ ] It displays the options "Image"
- [x] It opens the file browser
- [x] It allows to upload png and jpgs as a gif
- [x] Image is added in the next block
- [x] Images can be drag/dropped after
- [ ] The Image is centered within it's block (it might be worth it to wrap the image within a <p> tag)

## Next Steps

- When clicking plus there will be a dropdown first, asking the users for what to add: Image, Title, Paragraph, List, Video etc.

**Comment by ReneCode** [comment]
First Try:

https://user-images.githubusercontent.com/1595098/128923573-d08e8154-55f2-400e-8b7d-d3a96e05e24c.mov

**Comment by ReneCode** [comment]
first version in production - improvements with new issues
