### ISSUE TITLE
Copy + Paste on a block should duplicate it

### ISSUE THREAD

**Issue by Vannsl** [Vannsl/vue-contenteditable-form#16]
# Story

As a user, I want to duplicate a block by clicking Cmd C + Cmd V (macos Example. Should work for all OSs)

## Acceptance Criteria

- When copy/pasting a block, not matter if text, image or else, should be added right below the current block.
- Exception: Page title

**Comment by ReneCode** [comment]
hmm, not so easy I though.
- copy will set block-data as json into clipboard
- paste will parse that cliboard-json and create a new block below the current one. to not-paste the json-string into the current block ```event.preventDefault()``` is called.

that is the happy path. but:
- if in the clipboard is a normal text (no block-json) than the default paste behaviour should be triggered
- so *no* ```event.preventDefault()``` has to be called.
- that decision call or not call ```event.preventDefault()``` has to be made *synchronous* !
- but getting the data out of the clipboard is an async function :-(

any ideas ?

**Comment by Vannsl** [comment]
Not out of the box, but I will do some research. Do you already have a branch?

**Comment by ReneCode** [comment]
yes I have already a branch. I'll can make a PR - but not for merging in to main :-)

**Comment by ReneCode** [comment]
PR: #25 is on the road.
