### ISSUE TITLE
cursor up/down not working on images

### ISSUE THREAD

**Issue by ReneCode** [Vannsl/vue-contenteditable-form#22]
I see two solutions:

- ignore the image-block and jump to the next none-image-block
- make it possible to have the image-block been the "current" block. (usefull to delete the image-block with <backspace>). the next cursor up/down then will than leave this image-block and jump to the next block

**Comment by Vannsl** [comment]
I prefer "make it possible to have the image-block been the "current" block. (usefull to delete the image-block with ). the next cursor up/down then will than leave this image-block and jump to the next block"

what's your opinion?

**Comment by ReneCode** [comment]
yes agreed. I like the solution in PR #27 .   image-block is selectable and deletable - very good!
