### ISSUE TITLE
cursor down on empty text block should jump to next block if there is any

### ISSUE THREAD

**Issue by Vannsl** [Vannsl/vue-contenteditable-form#26]
# Bug & History

Focusing next block doesn't work when current block is an empty string. This behavior was implemented to prevent using cursor down-down-down to create a lot of useless empty blocks.

## Expected Behavior

When a text block is empty but there is a next block, it doesn't focus this next block.

## Actual Behavior

When a text block is empty but there is a next block, it doesn't focus this next block.

https://user-images.githubusercontent.com/5849721/131220230-c3b94c1b-3060-49cc-a3e0-ea0bbb50075b.mov

**Comment by ReneCode** [comment]
I agree
