### ISSUE TITLE
blocks should be deletable

### ISSUE THREAD

**Issue by ReneCode** [Vannsl/vue-contenteditable-form#5]
Ideas:

I see two ways of deleting a block:
- press ``Backspace`` on an empty the block
- special button (left of the drag-gripper) looking like a waste bin

tally.so does deleting the current block on pressing ``Backspace`` if the cursor in at the start of the block. Then the block is deleted and - if there was any text right of the cursor - the deleted text will be contacted to the block **before** the current block.

may be we start with ``Backspace`` on an empty block.

**Comment by Vannsl** [comment]
I like the idea of pressing "back" at the beginning of a block to delete it or merge it with the block before. With that I realized hitting "enter" in the middle of a block should bring the text to a block in the next line as well.

**Comment by Vannsl** [comment]
I implemented the bin-icon-to-delete-block here: [https://github.com/Vannsl/vue-contenteditable-form/pull/6](https://github.com/Vannsl/vue-contenteditable-form/pull/6)
