### ISSUE TITLE
Use / to add a title

### ISSUE THREAD

**Issue by Vannsl** [Vannsl/vue-contenteditable-form#9]
# Story

As a user, I want to be able to turn a field into a title.

## Description

When starting a block with `/` a popover opens. This popover shows the option "title". When the user selects `title`, the HTML block should be converted from a `<p>` to an `<h2>`. The design is open for imagination, something less big than the `<h1>` of the page title.

## Details

For now, this only needs to work when the block itself is still empty. Tally.so creates a new block below when using the / shorthand in a block with content.

## Next Steps

- "Turn into" action next to delete-action
- Subtitle with `<h3>`

**Comment by ReneCode** [comment]
sounds good. 
It should be possible to create a block with only "/" as content. just be ignoring the popover.

**Comment by ReneCode** [comment]
I'll give it a try. The hardest thing will be the popover, because I'm bad in CSS - so time to learn :-)

**Comment by Vannsl** [comment]
Thanks @ReneCode! If you start working on it, would you mind assigning the issue to yourself please?

**Comment by Vannsl** [comment]
P.S. I also added projects now! So you can use the basic cols To do + in progress + done for cards.

**Comment by ReneCode** [comment]
Is there a convention how to name branches and commits?
There seems to be something like 'fix' 'feat', ... but I have no clue how to name it consistent.

**Comment by Vannsl** [comment]
Hm, yeah, I usually use `chore/`, `fix/` and `feature/` prefixes for branches, but I also don't really care about what others are doing. For commits I try my best to write [conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0/) as they could be used for a change log - and are easier to revert/find issue.

**Comment by ReneCode** [comment]
should we close this "issue" ? I think the first step is done - but the "next steps" not  (subtitle, and turn-into)

**Comment by ReneCode** [comment]
I'll close that issue.
new issue => new feature => new code
